### ISSUE TITLE
Build pack URL for .NET Mono

### ISSUE THREAD

**Issue by aniljain100** [monostream/cf-monocloud-mono#3]
Hi,

I am trying to push .NET 4.5.2 app on cf.

I am using the below command:

cf push consoleapp -b "<Need .NET mono build pack url>"

Can you please give me the URL for .NET mono for the above command. The mono build URL isn't available on this page https://github.com/monostream/cf-monocloud-mono 

Please help me!

Thanks

**Comment by adrianliechti** [comment]
ciao aniljain,

try this: -b "https://github.com/monostream/cf-monocloud-mono#mono-4.2.3.4-gc"
the #value is the branch - so you have a stable deployment and no surprises about changing masters 

cheers, adrian

**Comment by aniljain100** [comment]
Hi adrianliechti,

I did push with the below command:

cf push consoleapp -b "https://github.com/monostream/cf-monocloud-mono#mono-4.2.3.4-gc"

Still getting the same error:
 OUT App instance exited with guid 91560678-a4fa-4d70-9f0f-bc1880e1e588 payload: {"instance"=>"", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"2 error(s) occurred:\n\n* 2 error(s) occurred:\n\n* Codependent step exited\n* cancelled\n* cancelled", "crash_count"=>1, "crash_timestamp"=>1470671953358837263, "version"=>"2335d6af-22f4-4ae1-8661-04ed0bf51211"}

Thanks

**Comment by adrianliechti** [comment]
we use this buildpack to run our OWIN (http://owin.org) based HTTP applications on Cloud Foundry. It's not really supported or meant for general purpose. That's why I will close this issue.

it's hard to guess what "consoleapp" is from the available information.
maybe a logging framework (nlog etc.) or Console.WriteLine in a try/catch block helps you to analyse what exactly crashes. Cloud Foundry has a health manager and expects to have a HTTP server running on the tcp port specified by the "PORT" environment variable - else it assumes the application has not started and tries to restart it.

It can also help to try your application on osx or linux first with mono, to see everything is supported and working.

wish you all the best, adrian

**Comment by aniljain100** [comment]
I am fine with 4.6 or 4.5 but I need to run it. Its a basic Console Application with just one statement:

Console.Writeline("Hello 4.5 on Linux");

I am able to run this with the command: _mono ConsoleApplication1.exe_ but it crashes while trying to start an instance. It crashes the 3rd or 4th time trying to start instance..

I'll push a ASP.NET MVC and let you know the results.

Also, can you give me the URL of 4.4.2.11, so I'll try pushing it again ?
Hope I'll get some help!!

Thanks
